### ISSUE TITLE
Enabling extension disables window minimizing

### ISSUE THREAD

**Issue by tonylom3** [hermes83/compiz-alike-magic-lamp-effect#1] opened 2020-11-02 22:06 UTC
Hello, I downloaded and enabled "compiz-alike-magic-lamp-effecthermes83.github.com.v2.shell-extension". After switching the little slider to "on" I could no longer minimize windows. Switching it off and rebooting resolved the issue. Ubuntu 18.04.5 LTS and gnome-shell version 3.28.4 on wayland.

Thank you,
-Tony

**Comment by hermes83** [comment] 2020-11-03 12:22
Hi, can you please try the following?

in file:
~/.local/share/gnome-shell/extensions/compiz-alike-magic-lamp-effect@hermes83.github.com/monitorUtils.js

change the following line (13):
this.scale = global.display.get_monitor_scale(monitorIndex);

with this one:
this.scale = 1;

then logout and login again.

**Comment by tonylom3** [comment] 2020-11-03 13:51
Sadly, that seemed to have no effect. It's like the windows just freeze and none of the controls work after enabling the extension.

![compiz-alike-magic-lamp](https://user-images.githubusercontent.com/11875810/97993116-a0da2580-1db1-11eb-92c5-99d743c10e77.png)

**Comment by hermes83** [comment] 2020-11-07 22:06
@tonylom3 the issue is fixed with the last commit.
It will be released on the gnome extensions portal in the next few days

**Closed by hermes83** 2020-11-07 22:06 UTC

**Comment by tonylom3** [comment] 2020-11-12 18:56
Hey! It works - very cool! Thank you.

-Tony
